package com.techlab.ecommerce.order.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Idempotency record for an inbound saga event. The natural key is {@code eventId}
 * (UUID generated by the producer in {@link com.techlab.ecommerce.common.messaging.envelope.EventEnvelope}).
 * Insertion is the idempotency check: the unique constraint on the primary key makes a
 * duplicate consumer delivery raise a {@code DataIntegrityViolationException} which the
 * consumer translates to "already processed, ack and skip".
 *
 * <p>This entity intentionally does not extend {@code BaseEntity} — there is no business
 * version/lifecycle here, just a marker row.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "processed_events")
public class ProcessedEvent {

    @Id
    @Column(name = "event_id", nullable = false, length = 100, updatable = false)
    private String eventId;

    @Column(name = "event_type", nullable = false, length = 100)
    private String eventType;

    /** Logical name of the consumer that handled the event (queue or service component). */
    @Column(name = "consumer", nullable = false, length = 100)
    private String consumer;

    @CreatedDate
    @Column(name = "processed_at", nullable = false, updatable = false)
    private Instant processedAt;
}
